# Generated by Django 2.1.15 on 2024-03-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('concert', 'Concert'), ('music_festival', 'Music Festival'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('exhibition', 'Exhibition'), ('album_release', 'Album Release'), ('live_stream', 'Live Stream'), ('meetup', 'Meetup')], max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('date_and_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
            ],
        ),
    ]
