# Generated by Django 2.1.15 on 2024-03-04 20:14

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
