version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - pip install --upgrade pip
            - pip install -r requirements.txt pylint
    pre_build:
        commands:
            - python --version
            - pylint --disable=C0103 $CODEBUILD_SRC_DIR/*.py
            - pylint --disable=C0103 $CODEBUILD_SRC_DIR/musicWebsite/*.py
            - pylint --disable=C0103 $CODEBUILD_SRC_DIR/events/*.py
artifacts:
    files:
        - '**/*'